// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCP_Foundation.Models;

namespace SCP_Foundation.Migrations
{
    [DbContext(typeof(SCPcontext))]
    [Migration("20221103195507_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SCP_Foundation.Models.SCP", b =>
                {
                    b.Property<int>("SCPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("ObjectClass")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("ThreatLevel")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("SCPID");

                    b.ToTable("SCPs");

                    b.HasData(
                        new
                        {
                            SCPID = 1,
                            IdNumber = "SCP-0003",
                            Name = "Biological Motherboard",
                            ObjectClass = "Euclid",
                            ThreatLevel = "Dark"
                        },
                        new
                        {
                            SCPID = 2,
                            IdNumber = "SCP-0013",
                            Name = "Wooden Statue",
                            ObjectClass = "Keter",
                            ThreatLevel = "Amida"
                        },
                        new
                        {
                            SCPID = 3,
                            IdNumber = "SCP-0023",
                            Name = "Oak Tree",
                            ObjectClass = "Archon",
                            ThreatLevel = "Vlam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
